// Generated by rstantools.  Do not edit by hand.

/*
    blackboxstudyR is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    blackboxstudyR is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with blackboxstudyR.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.18.0

#include <stan/model/model_header.hpp>

namespace model_twopl_namespace {

using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;

static int current_statement_begin__;

stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_twopl");
    reader.add_event(30, 28, "end", "model_twopl");
    return reader;
}

#include <stan_meta_header.hpp>
 class model_twopl : public prob_grad {
private:
    int I;
    int J;
    int N;
    vector<int> ii;
    vector<int> jj;
    vector<int> y;
public:
    model_twopl(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }

    model_twopl(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }

    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;

        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning

        current_statement_begin__ = -1;

        static const char* function__ = "model_twopl_namespace::model_twopl";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        // initialize member variables
        try {
            current_statement_begin__ = 2;
            context__.validate_dims("data initialization", "I", "int", context__.to_vec());
            I = int(0);
            vals_i__ = context__.vals_i("I");
            pos__ = 0;
            I = vals_i__[pos__++];
            current_statement_begin__ = 3;
            context__.validate_dims("data initialization", "J", "int", context__.to_vec());
            J = int(0);
            vals_i__ = context__.vals_i("J");
            pos__ = 0;
            J = vals_i__[pos__++];
            current_statement_begin__ = 4;
            context__.validate_dims("data initialization", "N", "int", context__.to_vec());
            N = int(0);
            vals_i__ = context__.vals_i("N");
            pos__ = 0;
            N = vals_i__[pos__++];
            current_statement_begin__ = 5;
            validate_non_negative_index("ii", "N", N);
            context__.validate_dims("data initialization", "ii", "int", context__.to_vec(N));
            validate_non_negative_index("ii", "N", N);
            ii = std::vector<int>(N,int(0));
            vals_i__ = context__.vals_i("ii");
            pos__ = 0;
            size_t ii_limit_0__ = N;
            for (size_t i_0__ = 0; i_0__ < ii_limit_0__; ++i_0__) {
                ii[i_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 6;
            validate_non_negative_index("jj", "N", N);
            context__.validate_dims("data initialization", "jj", "int", context__.to_vec(N));
            validate_non_negative_index("jj", "N", N);
            jj = std::vector<int>(N,int(0));
            vals_i__ = context__.vals_i("jj");
            pos__ = 0;
            size_t jj_limit_0__ = N;
            for (size_t i_0__ = 0; i_0__ < jj_limit_0__; ++i_0__) {
                jj[i_0__] = vals_i__[pos__++];
            }
            current_statement_begin__ = 7;
            validate_non_negative_index("y", "N", N);
            context__.validate_dims("data initialization", "y", "int", context__.to_vec(N));
            validate_non_negative_index("y", "N", N);
            y = std::vector<int>(N,int(0));
            vals_i__ = context__.vals_i("y");
            pos__ = 0;
            size_t y_limit_0__ = N;
            for (size_t i_0__ = 0; i_0__ < y_limit_0__; ++i_0__) {
                y[i_0__] = vals_i__[pos__++];
            }

            // validate, data variables
            current_statement_begin__ = 2;
            check_greater_or_equal(function__,"I",I,1);
            current_statement_begin__ = 3;
            check_greater_or_equal(function__,"J",J,1);
            current_statement_begin__ = 4;
            check_greater_or_equal(function__,"N",N,1);
            current_statement_begin__ = 5;
            for (int k0__ = 0; k0__ < N; ++k0__) {
                check_greater_or_equal(function__,"ii[k0__]",ii[k0__],1);
                check_less_or_equal(function__,"ii[k0__]",ii[k0__],I);
            }
            current_statement_begin__ = 6;
            for (int k0__ = 0; k0__ < N; ++k0__) {
                check_greater_or_equal(function__,"jj[k0__]",jj[k0__],1);
                check_less_or_equal(function__,"jj[k0__]",jj[k0__],J);
            }
            current_statement_begin__ = 7;
            for (int k0__ = 0; k0__ < N; ++k0__) {
                check_greater_or_equal(function__,"y[k0__]",y[k0__],0);
                check_less_or_equal(function__,"y[k0__]",y[k0__],1);
            }
            // initialize data variables


            // validate transformed data

            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 10;
            validate_non_negative_index("a", "I", I);
            num_params_r__ += I;
            current_statement_begin__ = 11;
            validate_non_negative_index("b", "I", I);
            num_params_r__ += I;
            current_statement_begin__ = 12;
            validate_non_negative_index("theta", "J", J);
            num_params_r__ += J;
            current_statement_begin__ = 13;
            ++num_params_r__;
            current_statement_begin__ = 14;
            ++num_params_r__;
            current_statement_begin__ = 15;
            ++num_params_r__;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    ~model_twopl() { }


    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        stan::io::writer<double> writer__(params_r__,params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;

        if (!(context__.contains_r("a")))
            throw std::runtime_error("variable a missing");
        vals_r__ = context__.vals_r("a");
        pos__ = 0U;
        validate_non_negative_index("a", "I", I);
        context__.validate_dims("initialization", "a", "vector_d", context__.to_vec(I));
        vector_d a(static_cast<Eigen::VectorXd::Index>(I));
        for (int j1__ = 0U; j1__ < I; ++j1__)
            a(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_lb_unconstrain(0,a);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable a: ") + e.what());
        }

        if (!(context__.contains_r("b")))
            throw std::runtime_error("variable b missing");
        vals_r__ = context__.vals_r("b");
        pos__ = 0U;
        validate_non_negative_index("b", "I", I);
        context__.validate_dims("initialization", "b", "vector_d", context__.to_vec(I));
        vector_d b(static_cast<Eigen::VectorXd::Index>(I));
        for (int j1__ = 0U; j1__ < I; ++j1__)
            b(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_unconstrain(b);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable b: ") + e.what());
        }

        if (!(context__.contains_r("theta")))
            throw std::runtime_error("variable theta missing");
        vals_r__ = context__.vals_r("theta");
        pos__ = 0U;
        validate_non_negative_index("theta", "J", J);
        context__.validate_dims("initialization", "theta", "vector_d", context__.to_vec(J));
        vector_d theta(static_cast<Eigen::VectorXd::Index>(J));
        for (int j1__ = 0U; j1__ < J; ++j1__)
            theta(j1__) = vals_r__[pos__++];
        try {
            writer__.vector_unconstrain(theta);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable theta: ") + e.what());
        }

        if (!(context__.contains_r("mu_b")))
            throw std::runtime_error("variable mu_b missing");
        vals_r__ = context__.vals_r("mu_b");
        pos__ = 0U;
        context__.validate_dims("initialization", "mu_b", "double", context__.to_vec());
        double mu_b(0);
        mu_b = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(mu_b);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable mu_b: ") + e.what());
        }

        if (!(context__.contains_r("sigmaB")))
            throw std::runtime_error("variable sigmaB missing");
        vals_r__ = context__.vals_r("sigmaB");
        pos__ = 0U;
        context__.validate_dims("initialization", "sigmaB", "double", context__.to_vec());
        double sigmaB(0);
        sigmaB = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,sigmaB);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable sigmaB: ") + e.what());
        }

        if (!(context__.contains_r("sigmaT")))
            throw std::runtime_error("variable sigmaT missing");
        vals_r__ = context__.vals_r("sigmaT");
        pos__ = 0U;
        context__.validate_dims("initialization", "sigmaT", "double", context__.to_vec());
        double sigmaT(0);
        sigmaT = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0,sigmaT);
        } catch (const std::exception& e) { 
            throw std::runtime_error(std::string("Error transforming variable sigmaT: ") + e.what());
        }

        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }

    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }


    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(vector<T__>& params_r__,
                 vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {

        typedef T__ local_scalar_t__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;

        try {
            // model parameters
            stan::io::reader<local_scalar_t__> in__(params_r__,params_i__);

            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  a;
            (void) a;  // dummy to suppress unused var warning
            if (jacobian__)
                a = in__.vector_lb_constrain(0,I,lp__);
            else
                a = in__.vector_lb_constrain(0,I);

            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  b;
            (void) b;  // dummy to suppress unused var warning
            if (jacobian__)
                b = in__.vector_constrain(I,lp__);
            else
                b = in__.vector_constrain(I);

            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  theta;
            (void) theta;  // dummy to suppress unused var warning
            if (jacobian__)
                theta = in__.vector_constrain(J,lp__);
            else
                theta = in__.vector_constrain(J);

            local_scalar_t__ mu_b;
            (void) mu_b;  // dummy to suppress unused var warning
            if (jacobian__)
                mu_b = in__.scalar_constrain(lp__);
            else
                mu_b = in__.scalar_constrain();

            local_scalar_t__ sigmaB;
            (void) sigmaB;  // dummy to suppress unused var warning
            if (jacobian__)
                sigmaB = in__.scalar_lb_constrain(0,lp__);
            else
                sigmaB = in__.scalar_lb_constrain(0);

            local_scalar_t__ sigmaT;
            (void) sigmaT;  // dummy to suppress unused var warning
            if (jacobian__)
                sigmaT = in__.scalar_lb_constrain(0,lp__);
            else
                sigmaT = in__.scalar_lb_constrain(0);


            // transformed parameters



            // validate transformed parameters

            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning

            // model body
            {
            current_statement_begin__ = 18;
            validate_non_negative_index("eta", "N", N);
            Eigen::Matrix<local_scalar_t__,Eigen::Dynamic,1>  eta(static_cast<Eigen::VectorXd::Index>(N));
            (void) eta;  // dummy to suppress unused var warning

            stan::math::initialize(eta, DUMMY_VAR__);
            stan::math::fill(eta,DUMMY_VAR__);


            current_statement_begin__ = 19;
            lp_accum__.add(lognormal_log<propto__>(a, 0.5, 1));
            current_statement_begin__ = 20;
            lp_accum__.add(normal_log<propto__>(b, mu_b, sigmaB));
            current_statement_begin__ = 21;
            lp_accum__.add(normal_log<propto__>(theta, 0, sigmaT));
            current_statement_begin__ = 22;
            for (int n = 1; n <= N; ++n) {
                current_statement_begin__ = 23;
                stan::model::assign(eta, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            (get_base1(a,get_base1(ii,n,"ii",1),"a",1) * (get_base1(theta,get_base1(jj,n,"jj",1),"theta",1) - get_base1(b,get_base1(ii,n,"ii",1),"b",1))), 
                            "assigning variable eta");
            }
            current_statement_begin__ = 24;
            lp_accum__.add(bernoulli_logit_log<propto__>(y, eta));
            current_statement_begin__ = 25;
            lp_accum__.add(normal_log<propto__>(mu_b, 0, 10));
            current_statement_begin__ = 26;
            lp_accum__.add(cauchy_log<propto__>(sigmaT, 0, 2.5));
            current_statement_begin__ = 27;
            lp_accum__.add(cauchy_log<propto__>(sigmaB, 0, 2.5));
            }

        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }

        lp_accum__.add(lp__);
        return lp_accum__.sum();

    } // log_prob()

    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }


    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("a");
        names__.push_back("b");
        names__.push_back("theta");
        names__.push_back("mu_b");
        names__.push_back("sigmaB");
        names__.push_back("sigmaT");
    }


    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dims__.push_back(I);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(I);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(J);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
    }

    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;

        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__,params_i__);
        static const char* function__ = "model_twopl_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        vector_d a = in__.vector_lb_constrain(0,I);
        vector_d b = in__.vector_constrain(I);
        vector_d theta = in__.vector_constrain(J);
        double mu_b = in__.scalar_constrain();
        double sigmaB = in__.scalar_lb_constrain(0);
        double sigmaT = in__.scalar_lb_constrain(0);
            for (int k_0__ = 0; k_0__ < I; ++k_0__) {
            vars__.push_back(a[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < I; ++k_0__) {
            vars__.push_back(b[k_0__]);
            }
            for (int k_0__ = 0; k_0__ < J; ++k_0__) {
            vars__.push_back(theta[k_0__]);
            }
        vars__.push_back(mu_b);
        vars__.push_back(sigmaB);
        vars__.push_back(sigmaT);

        // declare and define transformed parameters
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;

        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning

        try {



            // validate transformed parameters

            // write transformed parameters
            if (include_tparams__) {
            }
            if (!include_gqs__) return;
            // declare and define generated quantities



            // validate generated quantities

            // write generated quantities
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }

    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng,params_r_vec,params_i_vec,vars_vec,include_tparams,include_gqs,pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }

    static std::string model_name() {
        return "model_twopl";
    }


    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_0__ = 1; k_0__ <= I; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "a" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= I; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "b" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= J; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_b";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigmaB";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigmaT";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
        }


        if (!include_gqs__) return;
    }


    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        for (int k_0__ = 1; k_0__ <= I; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "a" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= I; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "b" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        for (int k_0__ = 1; k_0__ <= J; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta" << '.' << k_0__;
            param_names__.push_back(param_name_stream__.str());
        }
        param_name_stream__.str(std::string());
        param_name_stream__ << "mu_b";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigmaB";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigmaT";
        param_names__.push_back(param_name_stream__.str());

        if (!include_gqs__ && !include_tparams__) return;

        if (include_tparams__) {
        }


        if (!include_gqs__) return;
    }

}; // model

}

typedef model_twopl_namespace::model_twopl stan_model;


#endif
